DuplicateIDException: Take EntityIdentifier rather than int for the duplicate ID.
So we can use the same exception between both the legacy code, where fixtures
have a single int ID, and new code, where entities could be identified using any
EntityIdentifier object.