DuplicateIDException: Require line/column pair instead of Location parameter.
If we don't expose Location in our API, this class doesn't
need any special handling once we move the native("jvm")
annotation from the whole module to just the code that
needs it.